---
title: "SCI 2025: Homework 1"
format: 
  pdf:
    geometry: margin=1in
    fontsize: 12pt
    linestretch: 1.5
    include-in-header:
      text: |
        \usepackage{amsmath}
        \usepackage{amsfonts}
execute:
  echo: true
  warning: false
  message: false
---

## Setup

Imagine that you have performed an experiment where $N = 25$ chimpanzees watch a video of an interaction between an "agent" and a "patient". The agent leads the action of the scene, and the patient recieves or is affected by the action. Afterwards, the video is paused and the chimpanzees can touch either the agent or patient side of the screen. At the most basic level, you want to know: "Are chimpanzees more likely to touch the agent or patient side of the screen?".

Load the data into your R session:

```{r, echo=TRUE}
N_agent <- 14 # number of chimpanzees that touched the agent side
N_patient <- 11 # number of chimpanzees that touched the patient side
N_trials <- N_agent + N_patient
```

## Question 1

Using grid-approximation, compute the posterior distribution of the probability $p$ that the chimpanzees touch the agent side of the screen. The posterior should be represented with samples. Use a uniform prior for $p$.

## Question 2

With your posterior samples from Question 1:

(a) Compute and report the 90% credible interval (equal-tailed) for $p$.

(b) Compute and report the 90% highest posterior density interval for $p$.

(c) Compute and report the posterior mean for $p$.

(d) Compute and report the posterior probability that $p$ is greater than 0.5.

## Question 3

Repeat all the computations from Questions 1-2, but this time use a non-uniform prior. You are free to choose the prior, but you must justify your choice.

## Question 4

Visualize the prior and posterior distributions of $p$ from Questions 1-3.

## Question 5

Simulate 25 new observations of agent/patient touches, using the posterior distribution of $p$ from Question 3. How many of these simulations are agent vs patient? How closely does this compare to the actual data?

